FROM nikolaik/python-nodejs:python3.7-nodejs12

# Define arguments
ARG PIPENV_VENV_IN_PROJECT
ARG SECRET_KEY
ARG ALLOWED_HOSTS

ARG DJANGO_HOST
ARG DJANGO_PORT
ARG DEBUG
ARG JS_DEBUG
ARG LOCAL_DEV
ARG TEMPLATE_DEBUG

ARG PORT
ARG PRODUCTION
ARG NODE_ENV
ARG DEV_ENV

ARG DB_NAME
ARG DB_USER
ARG DB_HOST
ARG DB_PORT

# Make the arguments environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

ENV SECRET_KEY $SECRET_KEY
ENV ALLOWED_HOSTS $ALLOWED_HOSTS
ENV PIPENV_VENV_IN_PROJECT $PIPENV_VENV_IN_PROJECT

ENV DB_NAME $DB_NAME
ENV DB_USER $DB_USER
ENV DB_HOST $DB_HOST
ENV DB_PORT $DB_PORT

ENV DJANGO_HOST $DJANGO_HOST
ENV DJANGO_PORT $DJANGO_PORT
ENV DEBUG $DEBUG
ENV JS_DEBUG $JS_DEBUG
ENV LOCAL_DEV $LOCAL_DEV
ENV TEMPLATE_DEBUG $TEMPLATE_DEBUG
ENV PRODUCTION $PRODUCTION

ENV PORT $PORT
ENV NODE_ENV $NODE_ENV
ENV NPM_CONFIG_PRODUCTION $NPM_CONFIG_PRODUCTION
ENV DEV_ENV $DEV_ENV

# Create working directories
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy project
COPY . /usr/src/app

# Make sure yarn and pipenv are available
RUN npm i -g yarn
RUN pip install pipenv

# Copy package and package lock files
COPY package*.json yarn.lock Pipfile Pipfile.lock /usr/src/app/

# Now we install.
RUN pipenv install --system
RUN yarn install

# Expose a port
EXPOSE 3000 8000
