version: '3.7'

services:
  web:
    image: web
    build: .
    user: "node"
    environment:
      - NODE_ENV
    volumes:
      - nodejs:/usr/src/app
      - node_modules:/usr/src/app/node_modules/
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: npm run start
