version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: web
    volumes:
      - .:/user/src/app/
      - node_modules:/usr/src/app/node_modules
    networks:
      - frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV


networks:
  frontend:
  backend:

volumes:
  node_modules:
