# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-23 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160423_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=500)),
                ('skills', models.ManyToManyField(to='api.Skill')),
            ],
        ),
    ]
