# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160424_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
